version: '3.9'

services:
  db:
    image: library/postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pikabu
  web:
    build: .
    command: python /usr/src/pikabu_clone/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/pikabu_clone
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
volumes:
  postgres_data:

