# Generated by Django 3.2.6 on 2021-09-01 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                    to='posts.post', verbose_name='post the comment belongs to'),
            preserve_default=False,
        ),
    ]
